title: The Middle of All Things
description: Content management for meditations, stories, and book chapters

media:
  input: public/media
  output: public/media

collections:
  - label: Meditations
    name: meditations
    description: Guided meditation content
    path: src/meditations/meditations
    fields:
      - label: Title
        name: title
        type: string
        required: true
        description: The meditation title
      - label: Tags
        name: tags
        type: string
        required: true
        description: Comma-separated tags (e.g., paradox, infinity, emptiness)
      - label: Audio File
        name: audio
        type: file
        required: false
        description: Upload audio file (.wav format preferred)
      - label: Content
        name: content
        type: rich-text
        required: true
        description: The meditation content
    format: md
    newFile:
      filename: "{{slug}}"

  - label: Stories
    name: stories
    description: Philosophical stories and narratives
    path: src/stories/stories
    fields:
      - label: Title
        name: title
        type: string
        required: true
        description: The story title
      - label: Tags
        name: tags
        type: string
        required: true
        description: Comm-separated tags (e.g., consciousness, eternity, existence)
      - label: Audio File
        name: audio
        type: file
        required: false
        description: Upload audio file (.wav format preferred)
      - label: Content
        name: content
        type: rich-text
        required: true
        description: The story content
    format: md
    newFile:
      filename: "{{slug}}"

  - label: "Book - Introduction"
    name: book_introduction
    description: Introduction content
    path: src/book/introduction
    fields:
      - label: Title
        name: title
        type: string
        required: true
        description: Section title
      - label: Audio File
        name: audio
        type: file
        required: false
        description: Upload audio file (.wav format preferred)
      - label: Content
        name: content
        type: rich-text
        required: true
        description: Content
    format: md
    newFile:
      filename: "{{slug}}"

  - label: "Book - Part I: The Axis of Becoming"
    name: book_part_1
    description: Chapters for Part I
    path: "src/book/part-1" # Cleaned path
    fields:
      - label: Title
        name: title
        type: string
        required: true
        description: Chapter title
      - label: Audio File
        name: audio
        type: file
        required: false
        description: Upload audio file (.wav format preferred)
      - label: Content
        name: content
        type: rich-text
        required: true
        description: Chapter content
    format: md
    newFile:
      filename: "{{slug}}"

  - label: "Book - Part II: The Spiral Path"
    name: book_part_2
    description: Chapters for Part II
    path: "src/book/part-2" # Cleaned path
    fields:
      - label: Title
        name: title
        type: string
        required: true
        description: Chapter title
      - label: Audio File
        name: audio
        type: file
        required: false
        description: Upload audio file (.wav format preferred)
      - label: Content
        name: content
        type: rich-text
        required: true
        description: Chapter content
    format: md
    newFile:
      filename: "{{slug}}"

  - label: "Book - Part III: The Living Axis"
    name: book_part_3
    description: Chapters for Part III
    path: "src/book/part-3" # Cleaned path
    fields:
      - label: Title
        name: title
        type: string
        required: true
        description: Chapter title
      - label: Audio File
        name: audio
        type: file
        required: false
        description: Upload audio file (.wav format preferred)
      - label: Content
        name: content
        type: rich-text
        required: true
        description: Chapter content
    format: md
    newFile:
      filename: "{{slug}}"

  - label: "Book - Part IV: The Horizon Beyond"
    name: book_part_4
    description: Chapters for Part IV
    path: "src/book/part-4" # Cleaned path
    fields:
      - label: Title
        name: title
        type: string
        required: true
        description: Chapter title
      - label: Audio File
        name: audio
        type: file
        required: false
        description: Upload audio file (.wav format preferred)
      - label: Content
        name: content
        type: rich-text
        required: true
        description: Chapter content
    format: md
    newFile:
      filename: "{{slug}}"

  - label: "Book - Glossary"
    name: book_glossary
    description: Glossary entries
    path: src/book/glossary
    fields:
      - label: Title
        name: title
        type: string
        required: true
        description: Entry title
      - label: Audio File
        name: audio
        type: file
        required: false
        description: Upload audio file (.wav format preferred)
      - label: Content
        name: content
        type: rich-text
        required: true
        description: Content
    format: md
    newFile:
      filename: "{{slug}}"

  - label: "Book - Outro"
    name: book_outro
    description: Outro content
    path: src/book/outro.md # This is a single file
    fields:
      - label: Title
        name: title
        type: string
        required: true
        description: Section title
      - label: Audio File
        name: audio
        type: file
        required: false
        description: Upload audio file (.wav format preferred)
      - label: Content
        name: content
        type: rich-text
        required: true
        description: Content
    format: md
    # Removed 'newFile' block because this is a single file collection